# Read the docs config file v2
version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.7"

# Docs directory
sphinx:
  configuration: docs/conf.py

# Docs building deps
python:
  install:
    - requirements: docs/requirements.txt
